### ISSUE TITLE
Support for Skiller Mech SGK3 RGB?

### ISSUE THREAD

**Issue by CaptBlue** [DarthAffe/KeyboardAudioVisualizer#12]
Dont know if Sharkoon has SDK support, would be pretty nice if it could be supported, its a decent keyboard for the price and it already comes with a bunch of nice RGB-effects. Having an audio-visualizer for it would be neat.

**Comment by DarthAffe** [comment]
It doesn't seem like there is a SDK out there for sharkoon. Without this it won't be possible to include the device, sorry.
