### ISSUE TITLE
Problem with MM800 RGB POLARIS light bar

### ISSUE THREAD

**Issue by Xorgynoth** [DarthAffe/KeyboardAudioVisualizer#13]
Hi, I have a problem with my MM800 RGB POLARIS light bar.
The light bar works well on my K95 RGB PLATINIUM but nothing is displayed on the MM800 :/

Can you help me ? Thank you

**Comment by DarthAffe** [comment]
What version of CUE are you using?

**Comment by Xorgynoth** [comment]
I confirm, I have changed version and it works.

But I have another question is what is normal that there is a white led that lights up on the lightbar of my K95 when there is a beat while I select level?

**Comment by DarthAffe** [comment]
Yes, that's expected. It's because the lightbar has an odd amount of LEDs, the one in the center is surplus.

**Comment by Xorgynoth** [comment]
OK, thanks

**Comment by DarthAffe** [comment]
I've just created a new version which should work with iCUE
https://github.com/DarthAffe/KeyboardAudioVisualizer/releases/tag/v1.2
