### ISSUE TITLE
Frequency bars not functioning K70 rgb Vengeance 

### ISSUE THREAD

**Issue by thevipe** [DarthAffe/KeyboardAudioVisualizer#14]
I can get Level and Beat to work just fine, which indicates that there's no issue with the SDK or the keyboard. 

However, when I select Frequency Bars, the keyboard immediately goes blank, and fiddling around with the settings is no help. 

The application IS displaying the preview though, that is working.

**Comment by DarthAffe** [comment]
That's weird, if another effect is working it is (as you already said) not a problem with the sdk/device, but the preview shows exactly what's sent to the device so it's hard do believe that it's an issue with the effect iself Oo
Have you already tried to delete/rename the config file and check if it's working with default settings? Maybe there is something broken.

**Comment by thevipe** [comment]
Yes it's all on default settings I can even take a picture of the issue or video lol

On Sat, Jun 30, 2018, 2:02 PM DarthAffe <notifications@github.com<mailto:notifications@github.com>> wrote:

That's weird, if another effect is working it is (as you already said) not a problem with the sdk/device, but the preview shows exactly what's sent to the device so it's hard do believe that it's an issue with the effect iself Oo
Have you already tried to delete/rename the config file and check if it's working with default settings? Maybe there is something broken.

**Comment by DarthAffe** [comment]
Since there was another issue referring to that problem and I've really never heard of something like that I'm somehow suspicious that this problem is related to some external factor.
What version of CUE are you using? If I remember correctly there was a update lately, maybe it's related to that.

**Comment by YvesTM** [comment]
Thx for trying to fix this!

**Comment by Aida-Enna** [comment]
I'm having the same issue - Everything works great except the frequency bars visualizer, which is what I'm really excited about D: Using the latest iCUE.

**Comment by cgranados16** [comment]
Yup, I can say it is because of iCUE. I was using CUE2 and worked perfect but since i downloaded iCUE the Frequency bars are just blank.

**Comment by Aida-Enna** [comment]
I installed CUE2 (after uninstalling iCUE) and it works great (along with other things that were broken with iCUE)

**Comment by YvesTM** [comment]
can you make a version with the new sdk?

**Comment by DarthAffe** [comment]
I'm working on it, but I'm somehow unsure right now if that really fixes the issue since I've no problems using the the current release-version with iCUE - but we'll see.

**Comment by YvesTM** [comment]
Okey thanks

Op zo 8 jul. 2018 19:18 schreef DarthAffe <notifications@github.com>:

**Comment by ShaunTheBaa** [comment]
For a temporary solution guys, use this version of CUE:
https://www.dropbox.com/s/p9mkwb4genk22rl/%5BGuru3D.com%5D-Corsair-CUE.zip?dl=0
Or if you don't trust me download direct from 3D Guru:
http://www.guru3d.com/files-get/corsair-utility-engine-download,2.html

**Comment by DarthAffe** [comment]
I just created a new release which includes the new SDK. This should fix this problem and work with iCUE.
https://github.com/DarthAffe/KeyboardAudioVisualizer/releases/tag/v1.2

Please let me know if that's really the case.

**Comment by YvesTM** [comment]
it's working!!!

**Comment by thevipe** [comment]
yea its def working thanks for the update
