### ISSUE TITLE
support lighting node pro

### ISSUE THREAD

**Issue by YvesTM** [DarthAffe/KeyboardAudioVisualizer#17]
can you make support for the corsair lighting node pro?

**Comment by DarthAffe** [comment]
With the latest release (https://github.com/DarthAffe/KeyboardAudioVisualizer/releases/tag/v1.2) it should load lighting node devices (as long as they are correctly configured in iCUE) in the mouse/headset-category.

**Comment by YvesTM** [comment]
working thanks!
