### ISSUE TITLE
Doesn't Work with K55 and Harpoon RGB

### ISSUE THREAD

**Issue by Incrested** [DarthAffe/KeyboardAudioVisualizer#23]
I've got a Corsair K55 and Harpoon RGB (keyboard and mouse, respectively) and tried running the app with the keyboard visualization at the default frequency bars and the mouse on beat [detection]. I didn't expect the mouse to work as much as the keyboard. However, with iCUE both closed and opened when trying, this app didn't exactly function properly. I have the slight belief that it's due to the fact that the K55 has 3 RGB zones, but even something such as beat (which shouldn't require everywhere being able to be controlled) should work (but doesn't). I'm open to debugging or anything in VS if needed.

Kudos in advance for any and all help

**Comment by DarthAffe** [comment]
Hey, I need a bit more information what "didn't function properly" mean. Isn't it doing something at all? Are the devices turned black? Is the preview in the config window showing something or not? Is the preview in iCUE showing something?

**Comment by Incrested** [comment]
The devices stick with the default rainbow effect on both the mouse and keyboard. In the preview, it is the exact same as the actual lighting. The devices are also not detected, nor audio devices.

**Comment by Incrested** [comment]
SDK Support had been enabled, disabled and re-enabled multiple times, to no avail. I use the releases via this repo. iCUE runs while the app is open.

**Comment by DarthAffe** [comment]
In that case I'm afraid I can't help much. If the devices aren't even detected it's a problem with the SDK or the device-provider.
I don't think there's a way to solve that issue without debugging to see why it's not seeing any devices.
