### ISSUE TITLE
Auto-adjust Reference dB according to OS volume

### ISSUE THREAD

**Issue by rick-schubert** [DarthAffe/KeyboardAudioVisualizer#3]
Hi!

I really love your tool, it is absolutely amazing. I would like to forward a feature suggestion: currently, the user has to define a reference dB to adjust the height of the bars. Since users often change the OS volume, everytime the volume changes this has to be readjusted. Is there a way that the height of the bars perhaps just stay always in a certain range, as it is the case for the WinAmp equalizer for example?

Since things like these are always hard to explain in words, [I did also film a short video](https://youtu.be/8fnyAyM2Bq4) - I first play the song loud, then I turn my volume down. This makes the bars go down as well - it would be nice if this doesn't happen though.

**Comment by DarthAffe** [comment]
Hey,
I'm just working on this and it seems to be a really weird issue - I'm not able to reproduce it on my side, but such a problem was discussed in the issues of the audio-library I'm using too: [https://github.com/filoe/cscore/issues/86](https://github.com/filoe/cscore/issues/86)

I thought about adding a opt-in setting to counter that, but I'm not sure how exactly the windows settings affects the audio. Can you correct the volume issue by linear changing the reference in the settings?

**Comment by DarthAffe** [comment]
Hey
I was just able to reproduce this behavior. This seems to be related to the audio driver used to playback the audio. Some drivers (nvidia was the one that did that for me) are reducing the volume in the internal loopback-device. It doesn't seem like I'm able to correct this reduction correctly ... sorry.

**Comment by rick-schubert** [comment]
Hi @DarthAffe , sorry for the late reply. Thank you very much for having looked into it, that's much appreciated!

**Comment by DarthAffe** [comment]
Hey,
not sure if that was clear (considering my last reply) - I added something that should at least reduce the impact of the os-volume. It would be great to get some feedback on if/how good it works!
