### ISSUE TITLE
Support Steelseries Apex m750 (and m800 maybe)?

### ISSUE THREAD

**Issue by photonOne** [DarthAffe/KeyboardAudioVisualizer#44]
per key kb by Steelseries--should be fairly easy to support. Handlers are kind of complicated but there might be a lib to make it easier. I can help a bit if you decide to do this, or i might try to do this on a separate branch

**Comment by DarthAffe** [comment]
Hey, I just finished SteelSeries-support in RGB.NET (the library this is based on) (https://github.com/DarthAffe/RGB.NET/pull/52). To get the keyboard in I just need to know it's HID-id (for detection).
You can get it through the DeviceManager or with this Tool http://uploads.wyrez.org/HidGetter.zip

**Comment by photonOne** [comment]
oh haha, thats cool! thanks.
