### ISSUE TITLE
Using a k70 lux, lights never go off

### ISSUE THREAD

**Issue by ntenga** [DarthAffe/KeyboardAudioVisualizer#49]
What i mean it seems to be working, but if a button lights up it never goes off. until i close the app. It could be i am missing something any help would be appreciated. on the icue app i can see that SDK is enabled (which is obvious since it does seem to be working just not as intended) , I also have no lighting effects enabled so the keyboard is normally dark and only lights up if the visualizer lights up a button, but as i said it doesn't go away, so you just get a half light keyboard (depends on the visualization you have picked.), It could be i have a setting wrong into the visualizer? does it matter that this is keyboard has only one color? i don't think they are relevant. Thanks for any help.

**Comment by ntenga** [comment]
i should note that when using a musicbee plugin https://getmusicbee.com/addons/plugins/100/corsair-led-plugin/ it works with out a hitch. so it is probably this app or a setting that i am missing. I have the plugin disabled while trying using KeyboardAudioVisualizer.

**Comment by DarthAffe** [comment]
Hey, could you please attach the Settings.json and the error.log if it's present? Devices with only one color behave a bit different in some situations so it might be a blending issue.

**Comment by ntenga** [comment]
yeah sure, there was no error btw, also i could not link a .json file so i renamed it in .txt. i hope that isn't a problem, if it is i will try to make it a zip, but for some reason i couldn't, sorry i am not really proficient at these things


[Settings.txt](https://github.com/DarthAffe/KeyboardAudioVisualizer/files/3244695/Settings.txt)

**Comment by DarthAffe** [comment]
It seems like your background (in settings) has no alpha-value set. That's why it does override the set color with "nothing". If you've a single color keyboard, just set it to solid black and you should be fine.

**Comment by ntenga** [comment]
ok that did the trick, thank you, sorry if that was written somewhere and i missed it.
