### ISSUE TITLE
Colors "reset" upon restarting software

### ISSUE THREAD

**Issue by Halko-Proude** [DarthAffe/KeyboardAudioVisualizer#50]
Seems every time I restart the program all the colors settings are cleared and show a blank/black, this goes for each and every tab. I have to delete the settings.json file and restart so that it starts over with the default RGB colors, but then I have to re-add my customizations all over. I currently use a Logitech G810 keyboard, G502 mouse, and Corsair Void headset.

![image](https://user-images.githubusercontent.com/33703651/58906954-1b91a380-86db-11e9-9a6b-b2e9ae43ab80.png)

**Comment by strooth** [comment]
Same issue for me 
Win10 64bit
Corsair K95 Platinum (fw 3.21.7168)
icue 3.16.56
![2019-06-09 18_59_38-_new 4 - Notepad++](https://user-images.githubusercontent.com/13385030/59157161-3607ba80-8ae9-11e9-9a84-b9ae16b8e3fe.png)

**Comment by DarthAffe** [comment]
It seems like it looses the alpha-value (you should be able to fix it by setting it again in the color-picker), but this is obviously a bug. Does it really happen every time you restart or is it tied to an action or something?

**Comment by strooth** [comment]
So even if I extract the latest release fresh. Open (works) change nothing then close, (settings file created) open again and broken. Have to delete the settings file for it to work.
________________________________

**Comment by DarthAffe** [comment]
I just pushed a new version fixing this bug. If your settings are already corrupt you need to delete/recreate them one more time.

**Comment by Halko-Proude** [comment]
Just now was able to try again and works like a charm. Thank you DarthAffe :)

**Comment by strooth** [comment]
Yep, worked for me too, very cool!
________________________________
