### ISSUE TITLE
Program does not detect keyboard when running as a task in Task Scheduler

### ISSUE THREAD

**Issue by VintageCake** [DarthAffe/KeyboardAudioVisualizer#55]
Title pretty much explains it. The program works fine when started normally by double-clicking the exe, but scheduling the exe as a task in windows Task Scheduler opens the program but leaves the program unable to detect devices.

**Comment by DarthAffe** [comment]
That sounds like your execution directory in the action isn't correctly set and it's not able to find the SDK-dlls or it's started too early - without the vendor software running it won't detect devices.

**Comment by VintageCake** [comment]
You were correct, by setting execution directory correctly to the folder containing all the relevant files everything worked just fine, my bad. Thanks!

The reason why i wanted to schedule this program was that simply adding a shortcut to the executable in the startup folder just made the program start earlier than the iCUE software. With a task, a delay can be set for 1 or 2 minutes.
