### ISSUE TITLE
Ripped Project

### ISSUE THREAD

**Issue by DubStepMad** [DarthAffe/KeyboardAudioVisualizer#74]
Hey,

Not sure what to make of this but seems like someone is selling the program.

https://rgbeat.net/

**Comment by DarthAffe** [comment]
Hi, yeah I know about that, but since they release it still under gpl2 (https://rgbeat.net/?attribution and provide source code when requested - so no need to pay if you can compile it yourself :) - it's fine license-wise (even though I'm not 100% happy with it tbh).

**Comment by DubStepMad** [comment]
Hi, thanks for that/ I must have missed that page but either way I don't think its 100% right.
